name: publish to crates.io

on:
  push:
    tags:
      - 'derive-0.*'

env:
  CARGO_TERM_COLOR: always

jobs:
  release_mpesa_core:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true
    - name: Publish
      run: |
        cd mpesa_derive
        cargo doc
        cargo login ${{ secrets.CARGO_REGISTRY_TOKEN }}
        cargo publish
